name: adiixyzx404
title: adiixyzx404
description: JavaScript Deobfuscator and Unpacker
version: 1.12.0
author: Adiixyz
author_email: adiicotz@gmail.com
url: https://adiixyzx404.github.io
baseurl: /jsdu
repository: AdiixyzX404/adiixyzx404.github.io
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-106940288-1
sass:
  style: compressed

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "package.json",
    "package-lock.json",
    "Dockerfile",
    "docker-compose.yml",
    "docker-entrypoint.sh",
    "workbox-config.js"
  ]
incremental: false

environment: production
